server:
  port: 8080
  
spring:
  application:
    name: springbootShiro
  http:
    encoding:
      charset: UTF-8
      force: true
  
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/shirotest?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
        
  thymeleaf:
    cache: false  
    mode: LEGACYHTML5    
    
logging:
  level:
    root: info
    org.springframework.web: error
    org.hibernate: error
    com.zhumeng.shiro: debug    

  