server:
  port: 8080

spring:
  http:
    encoding:
      charset: UTF-8
      force: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: 127.0.0.1 #地址
    port: 6379 #端口
    database: 0 #数据库额索引默认0
    timeout: 0 #连接超时时间
    pool:
      max-active: 8 #连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 #连接池中的最大空闲连接
      min-idle: 0 #连接池中的最小空闲连接
      
    
logging:
  file: /log.log
  level:
    root: info
    org.springframework.web: info
    org.hibernate: error